// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8bKkv67SXsdz_BDLK2AmQX5xsxssmqpg',
    appId: '1:458368304727:web:3dd924b4b69bb3b10c8512',
    messagingSenderId: '458368304727',
    projectId: 'yamabiyori',
    authDomain: 'yamabiyori.firebaseapp.com',
    storageBucket: 'yamabiyori.firebasestorage.app',
    measurementId: 'G-YK93MKTVB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_iFqThifDiZp-gJ-3lk5JovIqCRSgQ9c',
    appId: '1:458368304727:android:b48e750db41cde020c8512',
    messagingSenderId: '458368304727',
    projectId: 'yamabiyori',
    storageBucket: 'yamabiyori.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgSGX7Ygiy-BoSPqta-Al9VQtxhwIVsQQ',
    appId: '1:458368304727:ios:92bbc2fa2948bd7a0c8512',
    messagingSenderId: '458368304727',
    projectId: 'yamabiyori',
    storageBucket: 'yamabiyori.firebasestorage.app',
    iosBundleId: 'com.example.yamabiyoriFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgSGX7Ygiy-BoSPqta-Al9VQtxhwIVsQQ',
    appId: '1:458368304727:ios:92bbc2fa2948bd7a0c8512',
    messagingSenderId: '458368304727',
    projectId: 'yamabiyori',
    storageBucket: 'yamabiyori.firebasestorage.app',
    iosBundleId: 'com.example.yamabiyoriFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8bKkv67SXsdz_BDLK2AmQX5xsxssmqpg',
    appId: '1:458368304727:web:3dd924b4b69bb3b10c8512',
    messagingSenderId: '458368304727',
    projectId: 'yamabiyori',
    authDomain: 'yamabiyori.firebaseapp.com',
    storageBucket: 'yamabiyori.firebasestorage.app',
    measurementId: 'G-YK93MKTVB8',
  );
}
