name: Deploy MountGo App (mountgo-app)

on:
  push:
    branches: [ main ]
    paths:
      - 'lib/**'
      - 'web/**'
      - 'assets/**'
      - 'pubspec.yaml'
      - '.github/workflows/deploy-mountgo-app.yml'
  workflow_dispatch:
    inputs:
      project_name:
        description: "Cloudflare Pages project name (default: mountgo-app)"
        required: false
        default: "mountgo-app"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Flutter Web (release)
        run: flutter build web --release --base-href "/"

      - name: Ensure Pages project exists (app)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: >-
            pages project create ${{ inputs.project_name || 'mountgo-app' }}
            --production-branch main
            --skip-guided-setup
        continue-on-error: true

      - name: List Pages projects (debug)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages project list

      - name: Deploy to Cloudflare Pages (app)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: >-
            pages deploy build/web
            --project-name ${{ inputs.project_name || 'mountgo-app' }}
            --branch main
            --commit-dirty=true
